### ISSUE TITLE
Make develop-nuxt the default devel branch

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-vue3#10]
Nuxt is a requirement so please rename it to develop or make this the default here on GitHub do all the development on that branch as soon as possible.

**Comment by ttechnicus** [comment]
As the window manager is set up, I'll merge this branch into develop

**Comment by ttechnicus** [comment]
Old develop branch was deleted.
The branch develop_nuxt was renamed to main.
A new develop branch was branched from main.
The branch feature/layout_redesign was branched from develop for the remaining work on the layout.
