### ISSUE TITLE
Transform window content typing to zod schemata

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-vue3#100]
Investigate how the current type inheritance can be implemented with zod

If it is feasible in a fitting time frame, transform the current typescript typing of the window contents to zod to enable runtime validation of parameters

**Comment by ctot-nondef** [comment]
@ttechnicus has there been any progress on this issue? can you document your findings here? thanks!

**Comment by ttechnicus** [comment]
Hi @ctot-nondef , so far I only had time to read the manual at zod.dev

**Comment by ttechnicus** [comment]
@ctot-nondef @simar0at  The types have been converted to zod schemas, and the code runs well right now. However, it would be nice to standardize the parameter names on the backend (see https://github.com/acdh-oeaw/vicav-app-api/issues/20) so that the arbitrary mappings can be removed here.

**Comment by ctot-nondef** [comment]
please move the zod definitions to a separate file (ie in the types folder as discussed)
