### ISSUE TITLE
Add tw-elements to stylelint ignore

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-vue3#105]
Stylelint floods the build log with warnings that are generated by the tw-elements plugin, e. g.:
```
 WARN  warn - The class data-[te-carousel-fade]:duration-[600ms] is ambiguous and matches multiple utilities.                                   11:44:27
 WARN  warn - If this is content and not a class, replace it with data-&lsqb;te-carousel-fade&rsqb;:duration-[600ms] to silence this warning.   11:44:27
...
```
Add tw-element to an ignore list of stylelint

**Comment by ttechnicus** [comment]
Status report: adding tw-element to .stylelintignore and similar ignore techniques do not solve the issue. The warnings are issued by the bundler when it is processing the js code of tw-elements

**Comment by ctot-nondef** [comment]
closing as tw-elements removed
