### ISSUE TITLE
Font rendering issues

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-vue3#136]
VICAV data frequently contains special characters, diacritics etc. which easily can lead to rendering issues when system fonts are used. This is the case for the TUNOCENT instance, for example. I assume the original implementation used a webfont to circumvent that problem, but evidently this is not the case for the vue3-implementation. Could you please look into that?

**Comment by VeronikaEngler** [comment]
<img width="396" alt="TUNOCENT_issue136" src="https://github.com/acdh-oeaw/vicav-vue3/assets/108801182/9c9bc989-02d5-4b49-932c-a9fc7072faee">

**Comment by dasch124** [comment]
Thanks for solving this!
