### ISSUE TITLE
optimize cross-examine features queries 

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-vue3#142]
empty or too loosely defined queries can kill the backend - need to investigate why and optimize query handling

**Comment by MauPalantir** [comment]
Rewritten the whole backend from scratch and refined the fronend. 
The current version discourages very generic queries (block you from submitting the form without a query criteria,
though you can still search data for the whole country) and even full Tunisia search does not seem to kill the backend, though the markers query is still not very fast.

Frontend was connected in thes PR:
https://github.com/acdh-oeaw/vicav-vue3/pull/163

New backend PR:
https://github.com/acdh-oeaw/vicav-app/pull/90
