### ISSUE TITLE
Session Persistance

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/vicav-vue3#15]
Decide on a strategy for session persistance ie localStorage

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html

**Comment by ttechnicus** [comment]
state persistance in URL is task #4

**Comment by ctot-nondef** [comment]
closed in favor of #4
