### ISSUE TITLE
TUNOCENT small Software fixes and additions

### ISSUE THREAD

**Issue by MauPalantir** [acdh-oeaw/vicav-vue3#167]
### Recordings Data table
- [x] Check Data Table region filter
- [x] Clear filters (data type especially)
- [x] Add Recording date
- [x] Interviewers
~- [ ] All Participants? (on hold, groundwork done)~
### Profiles
- [x] #182
- [x] Could the links fo Feature lists and smaple texts probably be sorted
- [x] Could the photo be aligned to the information box
- [x] Could "Contributed by" be in one line?
- [x] Space between pictures an text too small (e.g. Rouhia, Dahmani, Sbiba)
- [x] links to first two Feature lists in the Ain Draham profile don't work
### Comparison window
- [x]  When searching for a feature, display the highlighted word as well
- [x]  Age/sex filter doesn't seem to work
- [x]  Feature search results are too broad?
#### Corpus search
- [x]  add superscript vowels to the character bar
- [x]  Add autocomplete to corpus query widget
- [x]  Modify word autocompletion to yield broader results (for "a" -> superscript and long variants as well)
### Recordings list:  
- [x]  Add Speaker ID & demographics filter 
- [x] Display number of results
- [x] Transcribed corpus text list: too many whitespace!
- [x] #183
### Data list:
- [x] Ordering by speaker ID number
- [x] Missing place name headings by speaker ID number
- [x] acdh-oeaw/vicav-app#94

**Comment by dasch124** [comment]
Lists

- [ ] add counts of items to headings of lists (feature lists, samples) 
- [ ] lost location level in list hierarchy 
- [ ] feature lists list: when there are several informants, the _last_ speaker is provided as the label of the document
- [ ] Within the comparative search the feature is not highlighted in red.
- [ ] Query for age does not show correct results, same for male and
female.

**Comment by dasch124** [comment]
Lists

- [ ] add counts of items to headings of lists (feature lists, samples) 
- [ ] lost location level in list hierarchy 
- [ ] feature lists list: when there are several informants, the _last_ speaker is provided as the label of the document
- [ ] Within the comparative search the feature is not highlighted in red.
- [ ] Query for age does not show correct results, same for male and
female.

**Comment by dasch124** [comment]
compare feature lists: 

Make word autocompete insensitive to diacritics (inputting base character should find also base character with diacritics)

**Comment by dasch124** [comment]
compare feature lists:

"Place" searching only for governorate, locations are not shown in autocomplete

**Comment by dasch124** [comment]
searching for sample by number is broken

**Comment by dasch124** [comment]
all search windows: add a button "Open results in new window"

**Comment by dasch124** [comment]
feature search: word search returns duplicates of sentences > filter out
