### ISSUE TITLE
add option to toggle map from background into a window and vice versa

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-vue3#2]
In some cases, it will be useful to keep the map in the front while browsing the data, so ideally there should be a switch in the interface to put it into a window (and back again)

**Comment by ctot-nondef** [comment]
@dasch124 the background map is implemented, please specify the desired behaviour for the toggled maps behaviour, especially with regards to the menu points referring to map data.

I can think of the following options:

### Current: 
* All Map Data is being displayed in the background map, 
* a click on a menu point replaces the displayed data with the requested data

### Option 1: 
* upon toggling the map to a window, the background map remains in place, but is emptied of data
* clicking on a menu point loads new data to the background map
* toggling the background map to a window again opens another map window

### Option 2: 
_similiar to 1 but_
* toggling the background map to a window again replaces the current map window

### Option 3:
* upon toggling the map to a window, the background map is removed
* clicking on a menu point replaces the data in the current map window with the requested one

**Comment by ctot-nondef** [comment]
#5

**Comment by ctot-nondef** [comment]
after having a talk with @dasch124 we're implementing Option 3 but will open a new map window for every click on a geo link

**Comment by ctot-nondef** [comment]
@dasch124 I understand the baclkground map is to be dropped entirely, please advise the new spec in a separate issue or update this issue

**Comment by ttechnicus** [comment]
Task became obsolete and is being closed
