### ISSUE TITLE
Implement default ACDH-CH footer with info from imprint service

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-vue3#27]
We have to decide on a design level how the permanent footer and all the associated information should look like.
As a frontend dev my (Lev @ttechnicus) opinion is that a coherent SPA should not have "body scrollbars", only "component scrollbars", therefore the footer should be implemented as a bottom-up menu or an upwards opening "collapse" component. But I may not know all the standards set institution-wide on the ÖAW webpages, and/or specific demands from the "business side". Please let's make a decision what direction we should go.

**Comment by ctot-nondef** [comment]
create footer with fundament layout https://fundament.acdh.oeaw.ac.at/ and wire info from imprint service

**Comment by ctot-nondef** [comment]
Looks good so far, please use the [media queries](https://github.com/acdh-oeaw/fundament/blob/3c0fdef4dcb3ad86e811ed7ce848f4dea42a1502/src/sass/_partials/_variables.scss#L207) as suggested by fundament

**Comment by ttechnicus** [comment]
Added xl media query to footer; narrower screen breakpoints were already set.
As agreed personally in today's meeting, animation of the footer is in scope of task #63 , so this task can be closed with a successful merge
