### ISSUE TITLE
initial view

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-vue3#3]
On first load, the application should show the following in desktop mode:

* ~~Window Manager: arrange the windows according to some pre defined layouts (like three column as in [TUNICO corpus search](https://tunico.acdh.oeaw.ac.at/corpus.html))~~ see #12 
* ~~map in the background~~ feature regarded obsolete
* MISSION Text [with ACDH-CH contact information from included]
* VICAV Web-App: How to Use? [content of the horizontal bar under the map, cf https://github.com/acdh-oeaw/vicav-content/issues/20]

**Comment by ttechnicus** [comment]
Moved requirement about placement algorithm to its own task #12

**Comment by ttechnicus** [comment]
@simar0at The data for these windows to open on a fresh start should also come from the backend, in a data structure similar to the menu items.

**Comment by simar0at** [comment]
There is the `panel` array in the `projectConfig`

```json
		"panel": [
			{
				"id": "li_vicavMission",
				"target": "vicavMission",
				"title": "MISSION",
				"type": "panel",
				"targetType": "Text",
				"label": "Mission"
			},
			{
				"id": "li_vicavNews",
				"target": "vicavNews",
				"title": "NEWS",
				"type": "panel",
				"targetType": "Text",
				"label": "VICAV News"
			}
		]
```
