### ISSUE TITLE
Corpus components must use the new Compoisition API Syntax

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-vue3#34]
The CorpusQuery and CorpusText components still use the options API. This breaks in production when using `const { $api } = useNuxtApp();` `useNuxtApp()` only works in `<script setup lang="ts">` context.
```
Listening http://[::]:3000
[Vue Router warn]: uncaught error during route navigation:
Error: nuxt instance unavailable
    at useNuxtApp (file:///Users/simar/vicav-vue3/.output/server/chunks/app/server.mjs:160:13)
```
We also want to use the composition API as much as possible and the code looks much simpler when using it.
Please refer to https://vuejs.org/api/sfc-script-setup.html

**Comment by simar0at** [comment]
Steps to reproduce:
```bash
npm run build
npm run start
# new terminal
curl localhost:3000
```

**Comment by ttechnicus** [comment]
@simar0at This tasks seems very obsolete. We could close it by now.
