### ISSUE TITLE
state of the application should be shareable via URL

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-vue3#4]
Currently, the state of the application (number and order of opened windows, their content / queries) is encoded in the URL – this should be possible with the new implementation as well (it's not necessary to reproduce the current syntax)

**Comment by simar0at** [comment]
@ttechnicus and @ctot-nondef will solve this on 20.11.2023

**Comment by ctot-nondef** [comment]
state of the applications:
* the list of open windows and their respective content
* the windows arrangement
* if the arrangement is none, their sizes and positions

these need to be programmtically applicable on app bootstrap

**Comment by ttechnicus** [comment]
Other requirements:
- "zip" the windowStates

**Comment by ttechnicus** [comment]
The url length is growing currently with approx. 200 characters by each window open. Different browsers have different maximal length set for the url:
```
Browser     Address bar   document.location
                          or anchor tag
------------------------------------------
Chrome          32779           >64k
Android          8192           >64k
Firefox          >64k           >64k
Safari           >64k           >64k
IE11             2047           5120
Edge 16          2047          10240
```
([source](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers))

Therefore Internet Explorer and Edge users can experience strange behaviour after opening 10 windows. We judged this as an extremely rare user case which doesn't need to be treated as of now.

**Comment by simar0at** [comment]
This is closed now. Please move this comment to a new issue.

**Comment by ttechnicus** [comment]
@simar0at This is not a new issue, only a documentation of the work done
