### ISSUE TITLE
Content component: Map

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-vue3#44]
- Does it need to communicate with other components (e. g. adding layers of new pins after having mounted it)?

**Comment by ctot-nondef** [comment]
d/t adjustments in the backend the maps are currently broken, please fix before we merge #100

**Comment by ctot-nondef** [comment]
example for a correct geo query currently is: https://vicav.acdh-ch-dev.oeaw.ac.at/vicav/bibl_markers_tei?query=.*&scope=geo

to be discuzssed once omar is back, but we'll work with this query structure for now

**Comment by ttechnicus** [comment]
Branch `44-content-component-map` was created from branch `100-transform-window-content-typing-to-zod` and should be merged back into that instead of `develop`.

**Comment by ctot-nondef** [comment]
add a convenience function to map setting a zoom level that displays all markers in current window/map size

**Comment by ttechnicus** [comment]
Branch `44-content-component-map` has been merged back into branch `100-transform-window-content-typing-to-zod` so this issue can be closed
