### ISSUE TITLE
Meeting 2023-10-04

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-vue3#60]
Presented the window manager.
Menu behaves the same as original.
Different types of content need to be implemented one by one.
Text and dictionary are already implemented.
A few window arrangement options are implemented and can be previewed.
Dictionary query is partially implemented. Has at least one error.

Questions about map behaviour.
Multiple Maps?
What is to happen if the user selects data on the map.

Why do we have the background map: Initial window or background.
If we have a map open in a window and a background. What do we do?
Do we want to avoid opening the same data multiple times?

Brand colours.

Footer? How? Fundament?

Next major thing: State in the UI: Share links.

Background map: Toggle: 
* No map windows. Everything in the background
* Windows for everything.

Navigation bar as part of the map?

No map in the background.  All maps in windows. Map windows have a dynamic UI for layers. Custom generated queries will show up in the UI.
No hidden connection. Query windows have the query and the result below. Example: Bibl query: Text list results or map or both.

Wider windows for corpus search. 

No more deduplication of windows.

**Comment by ttechnicus** [comment]
- What are the actions implied by this task?
- How is this issue going to be closed? What are the conditions for closing?

**Comment by ttechnicus** [comment]
After discussion with @simar0at this issue can be closed.
