### ISSUE TITLE
Content component: Profile view

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-vue3#61]
create profile views like so https://vicav.acdh-ch-dev.oeaw.ac.at/vicav/#map=[biblMarkers,.*,geo]&1=[textQuery,vicavExplanationProfiles1,,open] and properly wire them to map ant profileList

**Comment by ctot-nondef** [comment]
in the current implementation the links of the profileList do not work

**Comment by simar0at** [comment]
Coordinates look strange:
Example:
Geo location	, 36, 43, 03, 05,

**Comment by ttechnicus** [comment]
@simar0at stylesheet is ready to test!
