### ISSUE TITLE
deduplicate text windwos

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/vicav-vue3#69]
All windows that display singlular texts should only be open once, when a link to such a window is clicked again it should bring the window to front and/or maxmize it.

text windows have parameters like so:
{"id":"vicavExplanationFeatures"}

**Comment by simar0at** [comment]
Roughly all windows that use an `id` parameter
* Explanation texts like Mission, News 
* Linguistic features windows 
* Language profile texts
* Corpus texts
Not deduplicated Windows:
* Maps (use id, should not)
* Query windows like dictionary searches

**Comment by ttechnicus** [comment]
I go with the "rule of thumb" that we agreed on, that whenever there is an "id" property in the parameters, the window should not open again, but get focus.

**Comment by ttechnicus** [comment]
branch 61 is merged into 69, so first we need to finish the PR for 61 before we do it for 69

**Comment by ctot-nondef** [comment]
basic functionality established, currently the effect if a text window already exists is `focus()` wich is not visible if the windows are in tiling mode, we need a more prominent effect such as a change in color
