### ISSUE TITLE
Content component: Feature

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-vue3#81]

**Comment by ttechnicus** [comment]
@simar0at The Feature list still has the links as data-target-type="External-link". This and the API needs fixing (there is no getFeature or similar method)

**Comment by simar0at** [comment]
[/vicav/ling_feature](https://vicav.acdh-ch-dev.oeaw.ac.at/openapi/#/vicav/vicav%3Aget_ling_feature)
