### ISSUE TITLE
Orchestrate windows using the apps state

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-vue3#9]
The layout of the windows on screen should depend on a property in the state of the app.
* create a state enginge (store) for the Window Manager

Beacause of this we should be able to
* ~~arrange the windows according to some pre defined layouts (like three column as in [TUNICO corpus search](https://tunico.acdh.oeaw.ac.at/corpus.html))~~
* ~~have an reactiv window menu that shows all open windows~~
* ~~can bring a window to the front if the user clicks on a link that references that window~~

**Comment by ttechnicus** [comment]
I move the first bullet to task #3 as it belongs to initialization

**Comment by ttechnicus** [comment]
I added a bullet as first for creating the state. This is a prerequisite for both the WM and the menu
I move the last two bullets to #11 as they belong there

**Comment by ttechnicus** [comment]
Inreferenced commits that contribute to the store: ac14ee658e658aa871656c9f7ee8fd3cd9efd4fb, 7c8b6decf0dc1096903c9e56b90719e39d99f800, e79d702f32876a1cfc25add4dac43cf5ab0cb976
